eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8071
spring:
  application:
    name: library
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/libraries
    username: postgres
    password: Open1sesame$
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    books-url: http://localhost:8223/api/v1/books

management:
  tracing:
    sampling:
      probability: 1.0